USE [master]
GO
CREATE LOGIN [VendorRO] WITH PASSWORD=N'Pa55w.rd', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [bulkadmin] ADD MEMBER [VendorRO]
GO
USE [Vendors]
GO
CREATE USER [VendorRO] FOR LOGIN [VendorRO]
GO
USE [Vendors]
GO
ALTER ROLE [db_datareader] ADD MEMBER [VendorRO]
GO
